# Generated by Django 3.1.7 on 2021-04-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210329_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('growth', models.CharField(choices=[('', 'Sunlight'), ('', 'Proper Temperature'), ('', 'Moisture'), ('', 'Air'), ('', 'Nutrients')], default=('', 'Sunlight'), max_length=50)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.flower')),
            ],
        ),
    ]
