# Generated by Django 3.1.7 on 2021-04-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_meals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
    ]
