# Generated by Django 3.1.7 on 2021-04-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210401_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='growth',
            field=models.CharField(choices=[('SL', 'Sunlight'), ('PT', 'Proper Temperature'), ('MT', 'Moisture'), ('A', 'Air'), ('NT', 'Nutrients')], default='SL', max_length=2),
        ),
    ]
