# Generated by Django 3.1.7 on 2021-04-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210401_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='flower_vase',
            new_name='vases',
        ),
    ]
